### ISSUE TITLE
Invalid email address gets validated

### ISSUE THREAD

**Issue by SorinGabriel02** [manishsaraan/email-validator#71] opened 2022-11-07 14:16 UTC
Hello.
I tried to validate `!!!!@gmail.com` and it goes trough as valid.
Is there any way to have an email name that contains only special characters before `@` or is this a bug?

**Comment by hogan** [comment] 2023-01-04 20:34
According to this, ! is valid character https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address

**Comment by houd1ni** [comment] 2023-03-05 05:29
@SorinGabriel02 As @hogan told, it is not a bug. But this email looks a bit malicious.

Would you suggest any ideas regarding API to the library or some checks that you would set to archive needs of more strict checking as optional parameters?

You welcome to reply here, - I'm closing the issue to keep the issues pool clean :bath:

**Closed** 2023-03-05 05:29 UTC
