### ISSUE TITLE
Invalid Top Level Domains are not caught

### ISSUE THREAD

**Issue by pere-pleo** [manishsaraan/email-validator#69] opened 2022-03-11 18:19 UTC
For instance: `test@test.comj` (notice the trailing `j`) is considered a valid email. This can conflict with other node validation libraries like `joi` used in the backend - the above would not pass joi's email test (see `tlds` prop [here](https://joi.dev/api/?v=17.6.0#stringemailoptions)) because `comj` is not listed in the [IANA registry](https://data.iana.org/TLD/tlds-alpha-by-domain.txt)

**Comment by houd1ni** [comment] 2023-05-29 09:44
Hi. Somehow mislooked this issue. Sozz. Thanks @jsangilve 4 bumping.

Also I suppose you use joi on server and email-validator on browser, right ?
If not, then use one algorithm everywhere.
Else, I would tell that the lib is not into somehow downloading fresh lists of everything including domains and checks only semantics. And trying do this on client would extremely load browsers. Have you ever checked how much Joi weights? 😄
For now I would suggest additionally manually check domains to keep an app clear.

However I'm thinking of how would be better to implement some plugins for such cases, including one below.
The issue is related to this one https://github.com/manishsaraan/email-validator/issues/70
Gonna tag y'all when it's done.  Closing this issue as enhancement request that's already being planned.
Feel free to write here anyway if any thoughts.

**Closed by houd1ni** 2023-05-29 09:44 UTC
