### ISSUE TITLE
Empty field not return error

### ISSUE THREAD

**Issue by FAngelo94** [manishsaraan/email-validator#61] opened 2021-11-16 11:14 UTC
If I enter with an empty field as email ("") it doesn't return error

**Comment by TandyN** [comment] 2022-01-06 15:54
Does it need to return an error? I tested this myself in node and it returns false as intended?

```
const validator = require('email-validator')

console.log(validator.validate(''))

// false
```

**Comment by houd1ni** [comment] 2023-03-05 06:14
@TandyN is right and it been some time to reply. Closing.

**Closed by houd1ni** 2023-03-05 06:14 UTC
